apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-server
  labels:
    app: chat-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-server
  template:
    metadata:
      labels:
        app: chat-server
    spec:
      containers:
        - name: chat-server
          image: tronxi/chat-server
          resources:
            limits:
              cpu: "0.9"
              memory: "900Mi"
            requests:
              cpu: "0.5"
              memory: "850Mi"
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
            
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 30
          env:
            - name: firebaseConfig
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: firebaseConfig
            - name: profile
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: profile
            - name: dbHost
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: dbHost
            - name: dbPort
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: dbPort
            - name: dbUser
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: dbUser
            - name: dbPassword
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: dbPassword
            - name: initializationMode
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: initializationMode
            - name: ddlAuto
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: ddlAuto
            - name: rabbitHost
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: rabbitHost
            - name: rabbitPassword
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: rabbitPassword
            - name: rabbitPort
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: rabbitPort
            - name: rabbitUser
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: rabbitUser
            - name: secretToken
              valueFrom:
                secretKeyRef:
                  name: chat-secret
                  key: secretToken
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: chat-server
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: chat-server
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 50
---
apiVersion: v1
kind: Service
metadata:
  name: chat-server
  labels:
    app: chat-server
spec:
  type: LoadBalancer
  selector:
    app: chat-server
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080