apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-front
  labels:
    app: chat-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-front
  template:
    metadata:
      labels:
        app: chat-front
    spec:
      containers:
        - name: chat-front
          image: tronxi/chat-front:latest
          resources:
            limits:
              cpu: "0.4"
              memory: "300Mi"
            requests:
              cpu: "0.1"
              memory: "100Mi"
          env:
            - name: serverUrl
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: serverUrl
            - name: serverWsUrl
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: serverWsUrl
            - name: baseRef
              valueFrom:
                configMapKeyRef:
                  name: chat-configmap
                  key: baseRef
---
apiVersion: v1
kind: Service
metadata:
  name: chat-front
  labels:
    app: chat-front
spec:
  type: LoadBalancer
  selector:
    app: chat-front
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80